public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        int a = 1200;
        System.out.println("Значение переменной a с типом int равно " + a);
        byte b = 3;
        System.out.println("Значение переменной a с типом byte равно " + b);
        short s = 230;
        System.out.println("Значение переменной a с типом short равно " + s);
        long r = 458L;
        System.out.println("Значение переменной a с типом long равно " + r);
        float f = 47.1646854486948f;
        System.out.println("Значение переменной a с типом float равно " + f);
        double blu = 20415;
        System.out.println("Значение переменной a с типом double равно " + blu);
        System.out.println();
        System.out.println("Задача 2");
        float pink = 27.12f;
        System.out.println(pink);
        long blue = 987678965549L;
        System.out.println(blue);
        float red = (float)2.786;
        System.out.println(red);
        short purple = 569;
        System.out.println(purple);
        short orange = -159;
        System.out.println(orange);
        int white = 27897;
        System.out.println(white);
        byte black = 67;
        System.out.println(black);
        System.out.println();
        System.out.println("Задача 3");
        byte luda = 23;
        System.out.println("У Людмилы Павловны — " + luda+ " ученика,");
        byte anna = 27;
        System.out.println("у Анны Сергеевны — " + anna+ " учеников?");
        byte katya = 30;
        System.out.println("У Екатерины Андреевны — " + katya+ " ученика.");
        short totalNumberOfStudents = (short)(luda + anna + katya);
        System.out.println("Всего " + totalNumberOfStudents+ " учеников");
        short addSheetsPaper = 480;
        System.out.println("Закуплено " + addSheetsPaper+ " листов бумаги на все три класса");
        short paperOneStudent = (short)(addSheetsPaper/totalNumberOfStudents);
        System.out.println("На каждого ученика рассчитано по " + paperOneStudent + " листов бумаги.");
        System.out.println();
        System.out.println("Задача 4");
        byte fabricated1Minute = 16 / 2;
        System.out.println("Средняя производительность машины равна " + fabricated1Minute+ " бутылок в 1 минуту");
        short fabricated20Minutes = (short)(20 * fabricated1Minute);
        System.out.println("За 20 минут машина произвела " + fabricated20Minutes+" штук бутылок,");
        int fabricated3Days = (3 * 24 * 60 * fabricated1Minute);
        System.out.println("За 3 дня машина произвела " + fabricated3Days+" штук бутылок,");
        int fabricatedMonth = (30 * 24 * 60 * fabricated1Minute);
        System.out.println("За 1 месяц машина произвела " + fabricatedMonth+" штук бутылок,");
        System.out.println();
        System.out.println("Задача 5");
        byte cansOfWhitePaitInOneClass = 2;
        byte cansOfBrownPaitInOneClass = 4;
        byte oneSetOfCans = (byte)(cansOfWhitePaitInOneClass + cansOfBrownPaitInOneClass);
        byte numberClass = (byte)(120 / oneSetOfCans);
        byte totalWhiteCans = (byte)(numberClass * cansOfWhitePaitInOneClass);
        byte totalBrownCans = (byte)(numberClass * cansOfBrownPaitInOneClass);
        System.out.println("В школе, где " + numberClass+" классов, нужно " + totalWhiteCans+" банок белой краски и " + totalBrownCans+ " банок коричневой краски.");
        System.out.println();
        System.out.println("Задача 6");
        byte bananaWeigthInGramms = 80;
        byte milkWeigthInGramms = 105;
        byte iceCreamWeigthInGramms = 100;
        byte eggWeigthInGramms = 70;
        short portionWeightInGramm = (short)((bananaWeigthInGramms*5)+(milkWeigthInGramms*2)+(iceCreamWeigthInGramms*2)+(eggWeigthInGramms*4));
        float  portionWeightInKilogramm = portionWeightInGramm/1000f;
        System.out.println("Вес спортивного завтрака составляет " + portionWeightInGramm+ " грамм, что соответствует " + portionWeightInKilogramm+ " килограмма.");
        System.out.println();
        System.out.println("Задача 7");
        int slowWeightLossKg = (int)(7/(250/1000f));
        System.out.println("Количество дней при медленном похудении составит " + slowWeightLossKg+ " дней,");
        int quickWeightLossKg = (int)(7/(500/1000f));
        System.out.println("Количество дней при более быстром похудении составит " + quickWeightLossKg+ " дней,");
        int averageNumberOfActions = (slowWeightLossKg + quickWeightLossKg)/2;
        System.out.println("В среднем потребуется " + averageNumberOfActions+ " день, чтобы добиться желаемого результата.");
        System.out.println();
        System.out.println("Задача 8");
        int salaryMasha = 67760;
        int salaryDenis = 83690;
        int salaryKristina = 76230;
        int newSalaryMashaInMonth = (int)(salaryMasha + ((10 * salaryMasha)/100f));
        int newPerYearSalaryMasha = 12 * (newSalaryMashaInMonth - salaryMasha);
        System.out.println("Теперь Маша получает " + newSalaryMashaInMonth+ " рублей в месяц. Годовой доход вырас на " + newPerYearSalaryMasha+ " рублей,");
        int newSalaryDenisInMonth = (int)(salaryDenis + ((10 * salaryDenis)/100f));
        int newPerYearSalaryDenis = 12 * (newSalaryDenisInMonth - salaryDenis);
        System.out.println("Теперь Денис получает " + newSalaryDenisInMonth+ " рублей в месяц. Годовой доход вырас на " + newPerYearSalaryDenis+ " рублей,");
        int newSalaryKristinaInMonth = (int)(salaryKristina + ((10 * salaryKristina)/100f));
        int newPerYearSalaryKristina = 12 * (newSalaryKristinaInMonth - salaryKristina);
        System.out.println("Теперь Кристина получает " + newSalaryKristinaInMonth+ " рублей в месяц. Годовой доход вырас на " + newPerYearSalaryKristina+ " рублей.");
    }
}